## Softmax

In [25]:
import numpy as np

In [26]:
#vector = np.array([11231,999,123142])

In [27]:
vector = np.array([-10, 30, 54])

In [28]:
np.exp(vector)

array([4.53999298e-05, 1.06864746e+13, 2.83075330e+23])

In [29]:
def softmax(vec):
    vec -= np.max(vec)
    exp = np.exp(vec)
    return exp / np.sum(exp)

In [30]:
softmax(vector)

array([1.60381089e-28, 3.77513454e-11, 1.00000000e+00])

In [45]:
vector = np.array([11231,999,123142,66666666])

In [50]:
def softmax(vec):
    #vec -= np.max(vec)
    exp = np.exp(vec)
    return exp / np.sum(exp)

In [51]:
softmax(vector)

D:\ProgramData2\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan, nan, nan, nan])

In [52]:
def softmax(vec):
    vec -= np.max(vec)
    exp = np.exp(vec)
    return exp / np.sum(exp)

In [53]:
softmax(vector)

array([0., 0., 0., 1.])

- ## Assignment-04 基于维基百科的词向量构建
在本章，你将使用Gensim和维基百科获得你的第一批词向量，并且感受词向量的基本过程。



- ### Step-01: Download Wikipedia Chinese Corpus: https://dumps.wikimedia.org/zhwiki/20190720/
第一步：使用维基百科下载中文语料库

- ### Step-02: Using https://github.com/attardi/wikiextractor to extract the wikipedia corpus
第二步：使用python wikipedia extractor抽取维基百科的内容

- ### Step-03: Using gensim get word vectors:
Reference:

- https://radimrehurek.com/gensim/models/word2vec.html
- https://www.kaggle.com/jeffd23/visualizing-word-vectors-with-t-sne
- 第三步：参考Gensim的文档和Kaggle的参考文档，获得词向量。 注意，你要使用Jieba分词把维基百科的内容切分成一个一个单词，然后存进新的文件中。然后，你需要用Gensim的LineSentence这个类进行文件的读取。

- 在训练成词向量Model.

- ### Step-04: Using some words to test your preformance.
第四步，测试同义词，找几个单词。

- ### Step-05: Using visualization tools: https://www.kaggle.com/jeffd23/visualizing-word-vectors-with-t-sne
第五步：使用Kaggle给出的T-SEN进行词向量的可视化。

In [54]:
 Step-01 Download wikipedia Chinese Corpus: 

In [ ]:
Step-02 : Using  https://github.com/attardi/wikiextractor to extract the wilipedia corpus 

In [22]:
!pip install langconv

  Could not find a version that satisfies the requirement langconv (from versions: )
No matching distribution found for langconv
You are using pip version 10.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [23]:
import langconv

ModuleNotFoundError: No module named 'langconv'

In [26]:
# -*- coding: utf-8 -*-
from gensim.corpora import WikiCorpus
import jieba
# from langconv import *
 
def my_function():
    space = ' '
    i = 0
    l = []
    zhwiki_name = "zhwiki-20190720-pages-articles-multistream.xml.bz2"
    f = open('C:/Users/tyx51/data/reduce_zhiwiki.txt', 'w',encoding='utf-8')
    wiki = WikiCorpus(zhwiki_name, lemmatize=False, dictionary={})   #从xml文件中读出训练语料
    for text in wiki.get_texts():
        for temp_sentence in text:
            #temp_sentence = Converter('zh-hans').convert(temp_sentence)   #繁体中文转为简体中文
            seg_list = list(jieba.cut(temp_sentence))  #分词
            for temp_term in seg_list:
                l.append(temp_term)
        f.write(space.join(l) + '\n')
        l = []
        i = i + 1
 
        if (i %200 == 0):  # 
            print('Saved ' + str(i) + ' articles')
    f.close()
 
if __name__ == '__main__':
    my_function()

D:\ProgramData2\Anaconda3\lib\site-packages\gensim\utils.py:1254: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\tyx51\AppData\Local\Temp\jieba.cache
Loading model cost 1.088 seconds.
Prefix dict has been built succesfully.


Saved 200 articles
Saved 400 articles
Saved 600 articles
Saved 800 articles
Saved 1000 articles
Saved 1200 articles
Saved 1400 articles
Saved 1600 articles
Saved 1800 articles
Saved 2000 articles
Saved 2200 articles
Saved 2400 articles
Saved 2600 articles
Saved 2800 articles
Saved 3000 articles
Saved 3200 articles
Saved 3400 articles
Saved 3600 articles
Saved 3800 articles
Saved 4000 articles
Saved 4200 articles
Saved 4400 articles
Saved 4600 articles
Saved 4800 articles
Saved 5000 articles
Saved 5200 articles
Saved 5400 articles
Saved 5600 articles
Saved 5800 articles
Saved 6000 articles
Saved 6200 articles
Saved 6400 articles
Saved 6600 articles
Saved 6800 articles
Saved 7000 articles
Saved 7200 articles
Saved 7400 articles
Saved 7600 articles
Saved 7800 articles
Saved 8000 articles
Saved 8200 articles
Saved 8400 articles
Saved 8600 articles
Saved 8800 articles
Saved 9000 articles
Saved 9200 articles
Saved 9400 articles
Saved 9600 articles
Saved 9800 articles
Saved 10000 articles
Sav

Saved 78800 articles
Saved 79000 articles
Saved 79200 articles
Saved 79400 articles
Saved 79600 articles
Saved 79800 articles
Saved 80000 articles
Saved 80200 articles
Saved 80400 articles
Saved 80600 articles
Saved 80800 articles
Saved 81000 articles
Saved 81200 articles
Saved 81400 articles
Saved 81600 articles
Saved 81800 articles
Saved 82000 articles
Saved 82200 articles
Saved 82400 articles
Saved 82600 articles
Saved 82800 articles
Saved 83000 articles
Saved 83200 articles
Saved 83400 articles
Saved 83600 articles
Saved 83800 articles
Saved 84000 articles
Saved 84200 articles
Saved 84400 articles
Saved 84600 articles
Saved 84800 articles
Saved 85000 articles
Saved 85200 articles
Saved 85400 articles
Saved 85600 articles
Saved 85800 articles
Saved 86000 articles
Saved 86200 articles
Saved 86400 articles
Saved 86600 articles
Saved 86800 articles
Saved 87000 articles
Saved 87200 articles
Saved 87400 articles
Saved 87600 articles
Saved 87800 articles
Saved 88000 articles
Saved 88200 a

Saved 154400 articles
Saved 154600 articles
Saved 154800 articles
Saved 155000 articles
Saved 155200 articles
Saved 155400 articles
Saved 155600 articles
Saved 155800 articles
Saved 156000 articles
Saved 156200 articles
Saved 156400 articles
Saved 156600 articles
Saved 156800 articles
Saved 157000 articles
Saved 157200 articles
Saved 157400 articles
Saved 157600 articles
Saved 157800 articles
Saved 158000 articles
Saved 158200 articles
Saved 158400 articles
Saved 158600 articles
Saved 158800 articles
Saved 159000 articles
Saved 159200 articles
Saved 159400 articles
Saved 159600 articles
Saved 159800 articles
Saved 160000 articles
Saved 160200 articles
Saved 160400 articles
Saved 160600 articles
Saved 160800 articles
Saved 161000 articles
Saved 161200 articles
Saved 161400 articles
Saved 161600 articles
Saved 161800 articles
Saved 162000 articles
Saved 162200 articles
Saved 162400 articles
Saved 162600 articles
Saved 162800 articles
Saved 163000 articles
Saved 163200 articles
Saved 1634

Saved 229000 articles
Saved 229200 articles
Saved 229400 articles
Saved 229600 articles
Saved 229800 articles
Saved 230000 articles
Saved 230200 articles
Saved 230400 articles
Saved 230600 articles
Saved 230800 articles
Saved 231000 articles
Saved 231200 articles
Saved 231400 articles
Saved 231600 articles
Saved 231800 articles
Saved 232000 articles
Saved 232200 articles
Saved 232400 articles
Saved 232600 articles
Saved 232800 articles
Saved 233000 articles
Saved 233200 articles
Saved 233400 articles
Saved 233600 articles
Saved 233800 articles
Saved 234000 articles
Saved 234200 articles
Saved 234400 articles
Saved 234600 articles
Saved 234800 articles
Saved 235000 articles
Saved 235200 articles
Saved 235400 articles
Saved 235600 articles
Saved 235800 articles
Saved 236000 articles
Saved 236200 articles
Saved 236400 articles
Saved 236600 articles
Saved 236800 articles
Saved 237000 articles
Saved 237200 articles
Saved 237400 articles
Saved 237600 articles
Saved 237800 articles
Saved 2380

Saved 303600 articles
Saved 303800 articles
Saved 304000 articles
Saved 304200 articles
Saved 304400 articles
Saved 304600 articles
Saved 304800 articles
Saved 305000 articles
Saved 305200 articles
Saved 305400 articles
Saved 305600 articles
Saved 305800 articles
Saved 306000 articles
Saved 306200 articles
Saved 306400 articles
Saved 306600 articles
Saved 306800 articles
Saved 307000 articles
Saved 307200 articles
Saved 307400 articles
Saved 307600 articles
Saved 307800 articles
Saved 308000 articles
Saved 308200 articles
Saved 308400 articles
Saved 308600 articles
Saved 308800 articles
Saved 309000 articles
Saved 309200 articles
Saved 309400 articles
Saved 309600 articles
Saved 309800 articles
Saved 310000 articles
Saved 310200 articles
Saved 310400 articles
Saved 310600 articles
Saved 310800 articles
Saved 311000 articles
Saved 311200 articles
Saved 311400 articles
Saved 311600 articles
Saved 311800 articles
Saved 312000 articles
Saved 312200 articles
Saved 312400 articles
Saved 3126

In [ ]:
# 中文 繁体转换的方法

In [ ]:
# from longconv import * 
# #temp_sentence = Converter('zh-hans').convert(temp_sentence)   #繁体中文转为简体中文 
#  上面的处理没有将  繁体转换为简体中文  估计是longconv 包的问题 

In [ ]:
step-03: Using gensim get word vectors;

In [ ]:
# -*- coding: utf-8 -*-
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence  # 对类的文件进行读取
import logging
 
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
 
def my_function():
    wiki_news = open('./data/reduce_zhiwiki.txt', 'r',encoding='utf-8')
    model = Word2Vec(LineSentence(wiki_news), sg=0,size=200, window=5, min_count=5, workers=6)
    model.save('./model/zhiwiki_news.word2vec')
 
if __name__ == '__main__':
    my_function()

D:\ProgramData2\Anaconda3\lib\site-packages\gensim\models\base_any2vec.py:743: UserWarning: C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.
  "C extension not loaded, training will be slow. "
2019-08-02 11:49:18,586 : INFO : collecting all words and their counts
2019-08-02 11:49:18,602 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2019-08-02 11:49:22,428 : INFO : PROGRESS: at sentence #10000, processed 12667629 words, keeping 860624 word types
2019-08-02 11:49:25,252 : INFO : PROGRESS: at sentence #20000, processed 21937749 words, keeping 1268044 word types
2019-08-02 11:49:27,864 : INFO : PROGRESS: at sentence #30000, processed 30235919 words, keeping 1569403 word types
2019-08-02 11:49:30,262 : INFO : PROGRESS: at sentence #40000, processed 37947556 words, keeping 1836978 word types
2019-08-02 11:49:32,516 : INFO : PROGRESS: at sentence #50000, processed 45196897 words, keeping 2071227 word types

2019-08-02 12:22:29,807 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 102 words/s, in_qsize 11, out_qsize 0
2019-08-02 12:22:37,209 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 107 words/s, in_qsize 12, out_qsize 0
2019-08-02 12:24:38,344 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 104 words/s, in_qsize 11, out_qsize 0
2019-08-02 12:25:40,682 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 104 words/s, in_qsize 11, out_qsize 0
2019-08-02 12:27:08,608 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 104 words/s, in_qsize 12, out_qsize 0
2019-08-02 12:29:28,570 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 101 words/s, in_qsize 11, out_qsize 0
2019-08-02 12:29:54,561 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 103 words/s, in_qsize 11, out_qsize 0
2019-08-02 12:30:17,794 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 106 words/s, in_qsize 12, out_qsize 0
2019-08-02 12:30:26,707 : INFO : EPOCH 1 - PROGRESS: at 0.03% examples, 108 words/s, in_qsize 12, out_qsize 0
2019-08-02

2019-08-02 13:52:16,544 : INFO : EPOCH 1 - PROGRESS: at 0.10% examples, 104 words/s, in_qsize 11, out_qsize 0
2019-08-02 13:52:25,268 : INFO : EPOCH 1 - PROGRESS: at 0.10% examples, 105 words/s, in_qsize 11, out_qsize 0
2019-08-02 13:54:48,823 : INFO : EPOCH 1 - PROGRESS: at 0.10% examples, 104 words/s, in_qsize 11, out_qsize 0
2019-08-02 13:55:38,373 : INFO : EPOCH 1 - PROGRESS: at 0.11% examples, 104 words/s, in_qsize 12, out_qsize 0
2019-08-02 13:55:47,550 : INFO : EPOCH 1 - PROGRESS: at 0.11% examples, 105 words/s, in_qsize 11, out_qsize 0


In [ ]:
Step-04: Using some words to test your preformance 

In [ ]:
#coding=utf-8
import gensim
import pandas as pd
def my_function():
 
    model = gensim.models.Word2Vec.load('./model/zhiwiki_news.word2vec')
    print(model.similarity('西红柿','番茄'))  #相似度为0.60256344
    print(model.similarity('西红柿','香蕉'))  #相似度为0.49495476
    # print(model.similarity('人工智能','大数据'))
    # print(model.similarity('滴滴', '共享单车'))
 
    result = pd.Series(model.most_similar(u'阿里巴巴')) #查找近义相关词
    print(result)
    result1 = pd.Series(model.most_similar(u'故宫'))
    print(result1)
    print(model.wv['中国']) #查看中国的词向量
 
if __name__ == '__main__':
    my_function()

In [ ]:
Step-05: Using visualization tools: (使用Sklearn 中TSNE进行词向量的可视化)

In [ ]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""
@author:Administrator
@file:Visualization.py
@time:2019/07/30
"""
import pandas as pd
pd.options.mode.chained_assignment = None
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence # 
from sklearn.manifold import 
import matplotlib.pyplot as plt
import logging
from matplotlib.font_manager import FontProperties
font = FontProperties(fname=r"c:\windows\fonts\simsun.ttc", size=14)
 
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
 
wiki_news = open('./data/reduce_zhiwiki.txt', 'r',encoding='utf-8')
model = Word2Vec(LineSentence(wiki_news), sg=0,size=200, window=10, min_count=500, workers=6)
print('model训练完成')
 
def tsne_plot(model):
    "Creates and TSNE model and plots it"
    labels = []
    tokens = []
    for word in model.wv.vocab:
        tokens.append(model[word])
        labels.append(word)
 
    tsne_model = TSNE(perplexity=40, n_components=2, init='pca', n_iter=2500, random_state=23)
    new_values = tsne_model.fit_transform(tokens)
    x = []
    y = []
    for value in new_values:
        x.append(value[0])
        y.append(value[1])
 
    plt.figure(figsize=(16, 16))
    for i in range(len(x)):
        plt.scatter(x[i], y[i])
        plt.annotate(labels[i],
                     fontproperties=font,
                     xy=(x[i], y[i]),
                     xytext=(5, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
    plt.show()
    tsne_plot(model)

In [ ]:
# 参考的其他的文章： 
# 参考 https://blog.csdn.net/weixin_40547993/article/details/97781179 
# 参考 https://mp.weixin.qq.com/s?__biz=Mzg3OTIwODUzMQ==&mid=2247483884&idx=1&sn=ac9bcdcf0ff0c829c4bde3c924793e23&chksm=cf06b0d0f87139c6b076c25f5ef62fa5e854fc1ba9ad7e6594d81247299afdc65bfdbc4d5a7f&mpshare=1&scene=1&srcid=&sharer_sharetime=1564700568936&sharer_shareid=8a7dda5da8b8c98c6da867326c7b6817&key=41fc1762f2cfaa707b7c448000c506e45a7bf6bf0c23cb878d3b8d7873ec0f18d354a5ffec693d9a84345966bcd71159ef5d0131287d02e176a1c4c47f7418eca2f602bb4faffaf750fc8595f0d2ea62&ascene=1&uin=OTY0MTYxNDA3&devicetype=Windows+10&version=62060833&lang=zh_CN&pass_ticket=OzApZSFEuQZvnAYUzn9ps5MSwVlQ4Lt1fwMT8Pf2dvlFbfJQUWAF1QlUqSBDCxWp
# 语料地址 ：百度云盘下载：
# 链接：https://pan.baidu.com/s/1q54CAKPQ1ZVTMtCZ5jWG6g 
# 提取码：bg2d 
# https://github.com/junnl/ai-nlp-test/tree/master/assignments_04

In [ ]:
# 加载模型找出指定词的相似词并制成词云

In [ ]:

#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""
@author:Administrator
@file:WordCloud_visualization.py
@time:2019/07/31
"""
 
import logging
from gensim import models
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
 
font_path = 'D:\Fonts\simkai.ttf'
 
'''
获取一个圆形的mask
'''
def get_mask():
    x, y = np.ogrid[:300, :300]
    mask = (x - 150) ** 2 + (y - 150) ** 2 > 130 ** 2
    mask = 255 * mask.astype(int)
    return mask
 
'''
绘制词云
'''
def draw_word_cloud(word_cloud):
    wc = WordCloud(font_path = font_path,background_color="white", mask=get_mask())
    wc.generate_from_frequencies(word_cloud)
    # 隐藏x轴和y轴
    plt.axis("off")
    plt.imshow(wc, interpolation="bilinear")
    plt.show()
 
def test():
    logging.basicConfig(format="%(asctime)s:%(levelname)s:%(message)s", level=logging.INFO)
    model = models.Word2Vec.load("./model/zhiwiki_news.word2vec")
    # 输入一个词找出相似的前100个词,默认是10个
    one_corpus = ["人工智能"]
    result = model.most_similar(one_corpus[0], topn=100)
    # 将返回的结果转换为字典,便于绘制词云
    word_cloud = dict()
    for sim in result:
        # print(sim[0],":",sim[1])
        word_cloud[sim[0]] = sim[1]
    # 绘制词云
    draw_word_cloud(word_cloud)
 
if __name__ == '__main__':

 

In [1]:
import gensim

In [ ]:
print("pandas 版本：",pd.__version__)
print("numpy 版本：",np.__version__)
print("gensim 版本", )